version: '3'

services:
  rabbitmq:
    image: rabbitmq:4-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672" # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: calendar
      RABBITMQ_DEFAULT_PASS: calendar
