log_level: debug
storage_type: sql
db:
  host: localhost
  port: 5432
  name: calendar
  username: calendar
  password: calendar
http_server:
  host: localhost
  port: 8081
grpc_server:
  host: localhost
  port: 8082